version: "3.5"
services:
  elasticsearch:
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms100m -Xmx100m
    image: elasticsearch:7.16.2
  postgresql:
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13
  temporal:
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_es.yaml
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
      - PROMETHEUS_ENDPOINT=0.0.0.0:8000
    image: temporalio/auto-setup:1.14.0
    ports:
      - 7233:7233
  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.14.0
    stdin_open: true
    tty: true
  temporal-web:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/temporal-web:rob-dataconverter
    ports:
      - 8088:8088
  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    build: './deployment/ui-server'
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./deployment/prometheus/config.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    build: './deployment/grafana'
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 8085:3000
    volumes:
      - type: bind
        source: ./deployment/grafana/provisioning/datasources
        target: /etc/grafana/provisioning/datasources
  mailhog:
    image: mailhog/mailhog:v1.0.1
    command: -invite-jim
    ports:
      - 8025:8025
  thirdparty:
    build: deployment/thirdparty-simulator
    command: thirdparty-simulator api
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  api:
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - DATACONVERTER_ENCRYPTION_KEY_ID=secret
  ui:
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  worker:
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - DATACONVERTER_ENCRYPTION_KEY_ID=secret
  tools:
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
  dataconverter-server:
    build:
      context: .
      target: app
    command: dataconverter-server http://localhost:8080
    restart: unless-stopped
    environment:
      - DATACONVERTER_ENCRYPTION_KEY_ID=secret
    ports:
      - 8081:8081
